---
title: "Homework Class 06"
author: "Keilyn Duarte (PID A16881868)"
format: pdf
---
## Homework

> Q. Can you improve this analysis code?

```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

```{r}
library(bio3d)

plot_protein_B <- function(protein) {
  #Search for a specific protein in pdb
  search <- read.pdb(protein)
  #Select alpha carbons from a particular chain
  trim <- trim.pdb(search, chain="A", elety="CA")
  #Select atom data
  atom_b <- trim$atom$b
  #Plot each residue (x-axis) to its B-factor value
  plotb3(atom_b, sse=trim, typ="l", ylab="Bfactor")
  
}
```

```{r}
#Apply your protein(s) to the function to get a residue vs. B-factor plot
sapply(c("4AKE","1AKE","1E4Y"), "plot_protein_B")
```


